# Generated by Django 4.1.2 on 2022-10-24 12:22

import app.design
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=20, null=True)),
                ('page', models.CharField(max_length=20)),
                ('referral', models.CharField(blank=True, max_length=10, null=True)),
                ('visit_duration', models.PositiveIntegerField()),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Активность',
                'verbose_name_plural': 'Активности',
            },
        ),
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4)),
                ('title', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to=app.design.upload_background_image)),
                ('video', models.ImageField(blank=True, null=True, upload_to=app.design.upload_background_video)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4)),
                ('active', models.BooleanField(default=True)),
                ('blockType', models.CharField(choices=[('link', 'Ссылка'), ('section', 'Раздел'), ('video', 'Видео'), ('music', 'Музыка'), ('document', 'Документ'), ('VKpub', 'ВК паблик'), ('TikTok Video', 'Видео из ТикТока'), ('Twitch', 'Twitch'), ('podcasts', 'Подкасты'), ('nft gallery', 'NFT Галерея'), ('Ymusic', 'Яндекс Музыка'), ('soundcloud', 'SoundCloud'), ('tips', 'Чаевые'), ('mobile app', 'Мобильное Приложение')], default='link', max_length=20)),
                ('url', models.CharField(blank=True, max_length=3000, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4)),
                ('title', models.CharField(max_length=20)),
                ('css', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4)),
                ('title', models.CharField(max_length=20)),
                ('css', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='LinkActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=20, null=True)),
                ('time_2click', models.PositiveIntegerField(verbose_name='Время проведенное до клика на кнопку [s]')),
                ('clicked_at', models.DateTimeField(auto_now_add=True, verbose_name='Момент нажатия')),
            ],
            options={
                'verbose_name': 'Активность блока',
                'verbose_name_plural': 'Активность блоков',
            },
        ),
        migrations.CreateModel(
            name='PageActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=20, null=True)),
                ('visit_duration', models.PositiveIntegerField(verbose_name='Время визита [s]')),
                ('referral', models.CharField(blank=True, max_length=10, null=True)),
                ('visited_at', models.DateTimeField(auto_now_add=True, verbose_name='Момент визита')),
            ],
            options={
                'verbose_name': 'Активность на ссылочке',
                'verbose_name_plural': 'Активность на ссылочках',
            },
        ),
        migrations.CreateModel(
            name='PageStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.PositiveIntegerField(default=0, verbose_name='Всего просмотров страницы')),
                ('total_clicks', models.PositiveIntegerField(default=0, verbose_name='Всего кликов по кнопкам')),
                ('total_time_spent', models.PositiveIntegerField(default=0, verbose_name='Время проведнное на странице [с]')),
                ('average_time', models.PositiveIntegerField(default=0, verbose_name='Среднее проведенное время на странице [с]')),
                ('average_time_2click', models.PositiveIntegerField(default=0, verbose_name='Среднее проведенное время до клика на кнопку [с]')),
            ],
            options={
                'ordering': ['total_views'],
            },
        ),
        migrations.CreateModel(
            name='ProfileActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=100)),
                ('next_page', models.CharField(max_length=100)),
                ('referral', models.CharField(blank=True, max_length=10, null=True)),
                ('visit_duration', models.PositiveIntegerField()),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Активность Профиля',
                'verbose_name_plural': 'Активность Профилей',
            },
        ),
        migrations.CreateModel(
            name='RedirectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('timezone', models.CharField(choices=[('+2', '+2 UTC | Калининградское время'), ('+3', '+3 UTC | Московское время')], default='+3', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['end_date', 'end_time'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4)),
                ('title', models.CharField(max_length=20)),
                ('premium', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField()),
                ('backgroundColor', models.CharField(blank=True, max_length=10, null=True)),
                ('backgroundGradient', models.TextField(blank=True, max_length=100, null=True)),
                ('background', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.background')),
                ('button', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.button')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('activity', models.ManyToManyField(blank=True, to='app.linkactivity')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_block', to='app.block')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='block',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blocks_link', to='app.link'),
        ),
        migrations.AddField(
            model_name='block',
            name='redirect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.redirectlink'),
        ),
    ]
