# Generated by Django 4.1.1 on 2022-10-21 12:16

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_redirectlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirectlink',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default=''),
            preserve_default=False,
        ),
    ]
