# Generated by Django 4.1.1 on 2022-10-21 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_redirectlink_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redirectlink',
            name='block',
        ),
        migrations.AddField(
            model_name='block',
            name='redirect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.redirectlink'),
        ),
        migrations.AlterField(
            model_name='redirectlink',
            name='timezone',
            field=models.CharField(choices=[('+2', '+2 UTC | Калининградское время'), ('+3', '+3 UTC | Московское время')], default='+3', max_length=3),
        ),
    ]
