# Generated by Django 4.1.1 on 2022-10-21 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_redirectlink_block_block_redirect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='url',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
