# Generated by Django 4.1.1 on 2022-10-21 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_block_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='url',
        ),
    ]
