# Generated by Django 4.1.1 on 2022-10-21 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='priorityLink',
            new_name='priority_link',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='redirectLink',
            new_name='redirect_link',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='updatedAt',
            new_name='updated_at',
        ),
    ]
