# Generated by Django 4.1.1 on 2022-10-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='w', max_length=254),
            preserve_default=False,
        ),
    ]
