# Generated by Django 4.1.1 on 2022-10-11 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='parent',
        ),
        migrations.AddField(
            model_name='category',
            name='subCategory',
            field=models.ManyToManyField(blank=True, to='user.subcategory'),
        ),
    ]
