# Generated by Django 4.1.2 on 2022-10-11 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_subcategory_parent_category_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='subcategory',
            new_name='subCategory',
        ),
    ]
