# Generated by Django 4.1.1 on 2022-10-13 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_avatar_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avatars_profile', to='user.profile'),
        ),
    ]
