# Generated by Django 4.1.1 on 2022-10-13 14:58

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_avatar_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.ua),
        ),
    ]
