# Generated by Django 4.1.1 on 2022-10-13 15:03

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_avatar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=1, upload_to=user.models.ua),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
