# Generated by Django 4.1.1 on 2022-10-13 15:20

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_avatar_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(default=1, upload_to=user.models.ua),
            preserve_default=False,
        ),
    ]
