# Generated by Django 4.1.1 on 2022-10-13 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0007_background_button_font_theme'),
        ('user', '0018_alter_profile_bio_alter_profile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='link.theme'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='background',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='link.background'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='button',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='link.button'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='font',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='link.font'),
        ),
        migrations.DeleteModel(
            name='Background',
        ),
        migrations.DeleteModel(
            name='Button',
        ),
        migrations.DeleteModel(
            name='Font',
        ),
    ]
