# Generated by Django 4.1.1 on 2022-10-10 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.URLField(blank=True, max_length=3000, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockType', models.CharField(choices=[('link', 'Ссылка'), ('section', 'Раздел'), ('video', 'Видео'), ('music', 'Музыка'), ('document', 'Документ'), ('VKpub', 'ВК паблик'), ('TikTok Video', 'Видео из ТикТока'), ('Twitch', 'Twitch'), ('podcasts', 'Подкасты'), ('nft gallery', 'NFT Галерея'), ('Ymusic', 'Яндекс Музыка'), ('soundcloud', 'SoundCloud'), ('tips', 'Чаевые'), ('mobile app', 'Мобильное Приложение')], default='link', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='link.link')),
            ],
        ),
    ]
