# Generated by Django 4.1.1 on 2022-10-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_alter_block_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
