# Generated by Django 4.1.1 on 2022-10-12 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0004_block_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='block',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='link_block', to='link.block'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='block',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='blocks_link', to='link.link'),
        ),
    ]
