# Generated by Django 4.1.1 on 2022-10-12 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0005_link_block_alter_block_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blocks_link', to='link.link'),
        ),
    ]
