# Generated by Django 4.1.1 on 2022-10-13 23:27

from django.db import migrations, models
import django.db.models.deletion
import link.design
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0006_alter_block_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4)),
                ('title', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to=link.design.ui)),
            ],
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4)),
                ('title', models.CharField(max_length=20)),
                ('css', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4)),
                ('title', models.CharField(max_length=20)),
                ('css', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4)),
                ('title', models.CharField(max_length=20)),
                ('premium', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField()),
                ('preview', models.ImageField(upload_to=link.design.up)),
                ('backgroundColor', models.CharField(blank=True, max_length=10, null=True)),
                ('backgroundGradient', models.TextField(blank=True, max_length=100, null=True)),
                ('background', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='link.background')),
                ('button', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='link.button')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
