# Generated by Django 4.1.1 on 2022-10-13 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0007_background_button_font_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='link.background'),
        ),
    ]
